version: '3.8'

services:
  malware-detection:
    image: cyber-def25-detector
    container_name: cyber-def25-detector
    volumes:
      - ./network_logs:/input/logs
      - ./output:/output
    environment:
      - TZ=Asia/Karachi
