version: '3.8'

services:
  malware-detection:
    build: .
    container_name: cyber-def25-detector
    volumes:
      # Mount host folder to container input
      - ./network_logs:/input/logs
      # Mount output folder to get results
      - ./output:/output
    environment:
      - TZ=Asia/Karachi
    restart: unless-stopped
